# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtplay.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QGridLayout,
    QLabel, QLineEdit, QListView, QMainWindow,
    QPushButton, QSizePolicy, QSlider, QSplitter,
    QWidget)
import icons_rc

class Ui_MainPlayer(object):
    def setupUi(self, MainPlayer):
        if not MainPlayer.objectName():
            MainPlayer.setObjectName(u"MainPlayer")
        MainPlayer.resize(963, 644)
        font = QFont()
        font.setFamilies([u"Hack"])
        font.setPointSize(14)
        font.setItalic(True)
        MainPlayer.setFont(font)
        self.widgetCentral = QWidget(MainPlayer)
        self.widgetCentral.setObjectName(u"widgetCentral")
        self.gridCentral = QGridLayout(self.widgetCentral)
        self.gridCentral.setObjectName(u"gridCentral")
        self.widgetBarra = QWidget(self.widgetCentral)
        self.widgetBarra.setObjectName(u"widgetBarra")
        self.widgetBarra.setMinimumSize(QSize(0, 40))
        self.widgetBarra.setMaximumSize(QSize(16777215, 40))
        self.widgetBarra.setStyleSheet(u"")
        self.gridBarra = QGridLayout(self.widgetBarra)
        self.gridBarra.setObjectName(u"gridBarra")
        self.gridBarra.setContentsMargins(0, 0, 0, 0)
        self.lbTitulo = QLabel(self.widgetBarra)
        self.lbTitulo.setObjectName(u"lbTitulo")
        self.lbTitulo.setMinimumSize(QSize(120, 0))
        self.lbTitulo.setMaximumSize(QSize(120, 16777215))
        self.lbTitulo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridBarra.addWidget(self.lbTitulo, 0, 0, 1, 1)

        self.btMenu = QPushButton(self.widgetBarra)
        self.btMenu.setObjectName(u"btMenu")
        self.btMenu.setMinimumSize(QSize(35, 0))
        self.btMenu.setMaximumSize(QSize(35, 16777215))
        icon = QIcon()
        icon.addFile(u":/views/icons/right-arrow.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btMenu.setIcon(icon)
        self.btMenu.setFlat(True)

        self.gridBarra.addWidget(self.btMenu, 0, 1, 1, 1)

        self.lbTituloArchivo = QLabel(self.widgetBarra)
        self.lbTituloArchivo.setObjectName(u"lbTituloArchivo")
        self.lbTituloArchivo.setIndent(14)

        self.gridBarra.addWidget(self.lbTituloArchivo, 0, 2, 1, 1)

        self.lbExtension = QLabel(self.widgetBarra)
        self.lbExtension.setObjectName(u"lbExtension")
        self.lbExtension.setMinimumSize(QSize(70, 0))
        self.lbExtension.setMaximumSize(QSize(70, 16777215))
        self.lbExtension.setTextFormat(Qt.TextFormat.RichText)
        self.lbExtension.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbExtension.setWordWrap(False)
        self.lbExtension.setMargin(0)
        self.lbExtension.setIndent(0)

        self.gridBarra.addWidget(self.lbExtension, 0, 3, 1, 1)

        self.btPin = QPushButton(self.widgetBarra)
        self.btPin.setObjectName(u"btPin")
        self.btPin.setMinimumSize(QSize(37, 37))
        self.btPin.setMaximumSize(QSize(37, 37))
        self.btPin.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/views/icons/pin-a.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btPin.setIcon(icon1)
        self.btPin.setIconSize(QSize(25, 25))
        self.btPin.setFlat(True)

        self.gridBarra.addWidget(self.btPin, 0, 4, 1, 1)

        self.btMin = QPushButton(self.widgetBarra)
        self.btMin.setObjectName(u"btMin")
        self.btMin.setMinimumSize(QSize(37, 37))
        self.btMin.setMaximumSize(QSize(37, 37))
        self.btMin.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/views/icons/minimize.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btMin.setIcon(icon2)
        self.btMin.setIconSize(QSize(25, 25))
        self.btMin.setFlat(True)

        self.gridBarra.addWidget(self.btMin, 0, 5, 1, 1)

        self.btMax = QPushButton(self.widgetBarra)
        self.btMax.setObjectName(u"btMax")
        self.btMax.setMinimumSize(QSize(37, 37))
        self.btMax.setMaximumSize(QSize(37, 37))
        self.btMax.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/views/icons/maximize.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btMax.setIcon(icon3)
        self.btMax.setIconSize(QSize(25, 25))
        self.btMax.setFlat(True)

        self.gridBarra.addWidget(self.btMax, 0, 6, 1, 1)

        self.btSquare = QPushButton(self.widgetBarra)
        self.btSquare.setObjectName(u"btSquare")
        self.btSquare.setMinimumSize(QSize(37, 37))
        self.btSquare.setMaximumSize(QSize(37, 37))
        self.btSquare.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/views/icons/square.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btSquare.setIcon(icon4)
        self.btSquare.setIconSize(QSize(25, 25))
        self.btSquare.setFlat(True)

        self.gridBarra.addWidget(self.btSquare, 0, 7, 1, 1)

        self.btClose = QPushButton(self.widgetBarra)
        self.btClose.setObjectName(u"btClose")
        self.btClose.setMinimumSize(QSize(37, 37))
        self.btClose.setMaximumSize(QSize(37, 37))
        self.btClose.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/views/icons/close.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btClose.setIcon(icon5)
        self.btClose.setIconSize(QSize(25, 25))
        self.btClose.setFlat(True)

        self.gridBarra.addWidget(self.btClose, 0, 8, 1, 1)

        self.btMin.raise_()
        self.btClose.raise_()
        self.btPin.raise_()
        self.btMax.raise_()
        self.lbTitulo.raise_()
        self.lbExtension.raise_()
        self.lbTituloArchivo.raise_()
        self.btSquare.raise_()
        self.btMenu.raise_()

        self.gridCentral.addWidget(self.widgetBarra, 0, 0, 1, 1)

        self.splitter = QSplitter(self.widgetCentral)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.frLista = QFrame(self.splitter)
        self.frLista.setObjectName(u"frLista")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frLista.sizePolicy().hasHeightForWidth())
        self.frLista.setSizePolicy(sizePolicy)
        self.frLista.setMinimumSize(QSize(300, 0))
        self.frLista.setMaximumSize(QSize(16777215, 16777215))
        self.frLista.setFrameShape(QFrame.Shape.StyledPanel)
        self.frLista.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLista = QGridLayout(self.frLista)
        self.gridLista.setObjectName(u"gridLista")
        self.gridLista.setHorizontalSpacing(3)
        self.ltLista = QListView(self.frLista)
        self.ltLista.setObjectName(u"ltLista")
        self.ltLista.setDragDropMode(QAbstractItemView.DragDropMode.DragDrop)

        self.gridLista.addWidget(self.ltLista, 0, 0, 1, 4)

        self.lnBuscar = QLineEdit(self.frLista)
        self.lnBuscar.setObjectName(u"lnBuscar")
        self.lnBuscar.setMinimumSize(QSize(0, 30))

        self.gridLista.addWidget(self.lnBuscar, 1, 0, 1, 4)

        self.btPrimero = QPushButton(self.frLista)
        self.btPrimero.setObjectName(u"btPrimero")
        self.btPrimero.setMinimumSize(QSize(57, 0))
        self.btPrimero.setMaximumSize(QSize(16777215, 16777215))
        self.btPrimero.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/views/icons/skip-up.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btPrimero.setIcon(icon6)
        self.btPrimero.setFlat(True)

        self.gridLista.addWidget(self.btPrimero, 2, 0, 1, 1)

        self.btSubir = QPushButton(self.frLista)
        self.btSubir.setObjectName(u"btSubir")
        self.btSubir.setMinimumSize(QSize(57, 0))
        self.btSubir.setMaximumSize(QSize(16777215, 16777215))
        self.btSubir.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/views/icons/play-up.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btSubir.setIcon(icon7)
        self.btSubir.setFlat(True)

        self.gridLista.addWidget(self.btSubir, 2, 1, 1, 1)

        self.btBajar = QPushButton(self.frLista)
        self.btBajar.setObjectName(u"btBajar")
        self.btBajar.setMinimumSize(QSize(57, 0))
        self.btBajar.setMaximumSize(QSize(16777215, 16777215))
        self.btBajar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/views/icons/play-dow.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btBajar.setIcon(icon8)
        self.btBajar.setFlat(True)

        self.gridLista.addWidget(self.btBajar, 2, 2, 1, 1)

        self.btUltimo = QPushButton(self.frLista)
        self.btUltimo.setObjectName(u"btUltimo")
        self.btUltimo.setMinimumSize(QSize(57, 0))
        self.btUltimo.setMaximumSize(QSize(16777215, 16777215))
        self.btUltimo.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btUltimo.setIcon(icon6)
        self.btUltimo.setIconSize(QSize(16, 16))
        self.btUltimo.setAutoRepeatDelay(299)
        self.btUltimo.setFlat(True)

        self.gridLista.addWidget(self.btUltimo, 2, 3, 1, 1)

        self.widgetBotones = QWidget(self.frLista)
        self.widgetBotones.setObjectName(u"widgetBotones")
        self.gridBotones = QGridLayout(self.widgetBotones)
        self.gridBotones.setObjectName(u"gridBotones")
        self.gridBotones.setHorizontalSpacing(3)
        self.gridBotones.setContentsMargins(0, 0, 0, 0)
        self.btAgregar = QPushButton(self.widgetBotones)
        self.btAgregar.setObjectName(u"btAgregar")
        self.btAgregar.setMinimumSize(QSize(70, 0))
        self.btAgregar.setMaximumSize(QSize(16777215, 16777215))
        self.btAgregar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridBotones.addWidget(self.btAgregar, 0, 0, 1, 1)

        self.btEliminar = QPushButton(self.widgetBotones)
        self.btEliminar.setObjectName(u"btEliminar")
        self.btEliminar.setMinimumSize(QSize(70, 0))
        self.btEliminar.setMaximumSize(QSize(16777215, 16777215))
        self.btEliminar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridBotones.addWidget(self.btEliminar, 0, 1, 1, 1)

        self.btOrdenar = QPushButton(self.widgetBotones)
        self.btOrdenar.setObjectName(u"btOrdenar")
        self.btOrdenar.setMinimumSize(QSize(70, 0))
        self.btOrdenar.setMaximumSize(QSize(16777215, 16777215))
        self.btOrdenar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridBotones.addWidget(self.btOrdenar, 0, 2, 1, 1)


        self.gridLista.addWidget(self.widgetBotones, 3, 0, 1, 4)

        self.splitter.addWidget(self.frLista)
        self.frPlayer = QFrame(self.splitter)
        self.frPlayer.setObjectName(u"frPlayer")
        sizePolicy.setHeightForWidth(self.frPlayer.sizePolicy().hasHeightForWidth())
        self.frPlayer.setSizePolicy(sizePolicy)
        self.frPlayer.setMinimumSize(QSize(0, 0))
        self.frPlayer.setFrameShape(QFrame.Shape.StyledPanel)
        self.frPlayer.setFrameShadow(QFrame.Shadow.Raised)
        self.gridPlayer = QGridLayout(self.frPlayer)
        self.gridPlayer.setObjectName(u"gridPlayer")
        self.gridPlayer.setHorizontalSpacing(6)
        self.gridPlayer.setContentsMargins(0, 0, 0, 0)
        self.widgetArchivos = QWidget(self.frPlayer)
        self.widgetArchivos.setObjectName(u"widgetArchivos")
        # self.widgetArchivos.setStyleSheet(u"background-color:  #aa007f;")
        self.gridArchivos = QGridLayout(self.widgetArchivos)
        self.gridArchivos.setObjectName(u"gridArchivos")
        self.lbLogo = QLabel(self.widgetArchivos)
        self.lbLogo.setObjectName(u"lbLogo")
        self.lbLogo.setMinimumSize(QSize(0, 0))
        self.lbLogo.setMaximumSize(QSize(16777215, 16777215))
        self.lbLogo.setSizeIncrement(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"Hack"])
        font1.setPointSize(36)
        font1.setBold(True)
        font1.setItalic(True)
        self.lbLogo.setFont(font1)
        self.lbLogo.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lbLogo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbLogo.setWordWrap(True)
        self.lbLogo.setMargin(2)

        self.gridArchivos.addWidget(self.lbLogo, 0, 0, 1, 1)


        self.gridPlayer.addWidget(self.widgetArchivos, 0, 0, 1, 1)

        self.lbMetas = QLabel(self.frPlayer)
        self.lbMetas.setObjectName(u"lbMetas")
        # self.lbMetas.setMinimumSize(QSize(0, 100))
        # self.lbMetas.setMaximumSize(QSize(16777215, 100))
        self.lbMetas.setMinimumSize(QSize(0, 16777215))
        self.lbMetas.setMaximumSize(QSize(16777215, 16777215))
        self.lbMetas.setFrameShape(QFrame.Shape.NoFrame)
        self.lbMetas.setWordWrap(True)

        self.gridPlayer.addWidget(self.lbMetas, 1, 0, 1, 1)

        self.splitter.addWidget(self.frPlayer)

        self.gridCentral.addWidget(self.splitter, 1, 0, 1, 1)

        self.widgetControles = QWidget(self.widgetCentral)
        self.widgetControles.setObjectName(u"widgetControles")
        self.widgetControles.setMinimumSize(QSize(0, 70))
        self.widgetControles.setMaximumSize(QSize(16777215, 70))
        self.gridControles = QGridLayout(self.widgetControles)
        self.gridControles.setObjectName(u"gridControles")
        self.gridControles.setHorizontalSpacing(3)
        self.gridControles.setContentsMargins(0, 0, 0, 0)
        self.slTiempo = QSlider(self.widgetControles)
        self.slTiempo.setObjectName(u"slTiempo")
        self.slTiempo.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.slTiempo.setOrientation(Qt.Orientation.Horizontal)

        self.gridControles.addWidget(self.slTiempo, 0, 0, 1, 15)

        self.btSkipBack = QPushButton(self.widgetControles)
        self.btSkipBack.setObjectName(u"btSkipBack")
        self.btSkipBack.setMinimumSize(QSize(37, 37))
        self.btSkipBack.setMaximumSize(QSize(37, 16777215))
        self.btSkipBack.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/views/icons/skip-back.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btSkipBack.setIcon(icon9)
        self.btSkipBack.setIconSize(QSize(25, 25))
        self.btSkipBack.setFlat(True)

        self.gridControles.addWidget(self.btSkipBack, 1, 0, 1, 1)

        self.btBack = QPushButton(self.widgetControles)
        self.btBack.setObjectName(u"btBack")
        self.btBack.setMinimumSize(QSize(37, 37))
        self.btBack.setMaximumSize(QSize(37, 16777215))
        self.btBack.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u":/views/icons/back.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btBack.setIcon(icon10)
        self.btBack.setIconSize(QSize(25, 25))
        self.btBack.setFlat(True)

        self.gridControles.addWidget(self.btBack, 1, 1, 1, 1)

        self.btPlay = QPushButton(self.widgetControles)
        self.btPlay.setObjectName(u"btPlay")
        self.btPlay.setMinimumSize(QSize(37, 37))
        self.btPlay.setMaximumSize(QSize(37, 16777215))
        self.btPlay.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u":/views/icons/play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btPlay.setIcon(icon11)
        self.btPlay.setIconSize(QSize(25, 25))
        self.btPlay.setFlat(True)

        self.gridControles.addWidget(self.btPlay, 1, 2, 1, 1)

        self.btStop = QPushButton(self.widgetControles)
        self.btStop.setObjectName(u"btStop")
        self.btStop.setMinimumSize(QSize(37, 37))
        self.btStop.setMaximumSize(QSize(37, 16777215))
        self.btStop.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u":/views/icons/stop.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btStop.setIcon(icon12)
        self.btStop.setIconSize(QSize(25, 25))
        self.btStop.setFlat(True)

        self.gridControles.addWidget(self.btStop, 1, 3, 1, 1)

        self.btForward = QPushButton(self.widgetControles)
        self.btForward.setObjectName(u"btForward")
        self.btForward.setMinimumSize(QSize(37, 37))
        self.btForward.setMaximumSize(QSize(37, 16777215))
        self.btForward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u":/views/icons/forward.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btForward.setIcon(icon13)
        self.btForward.setIconSize(QSize(25, 25))
        self.btForward.setFlat(True)

        self.gridControles.addWidget(self.btForward, 1, 4, 1, 1)

        self.btSkipForward = QPushButton(self.widgetControles)
        self.btSkipForward.setObjectName(u"btSkipForward")
        self.btSkipForward.setMinimumSize(QSize(37, 37))
        self.btSkipForward.setMaximumSize(QSize(37, 16777215))
        self.btSkipForward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon14 = QIcon()
        icon14.addFile(u":/views/icons/skip-forward.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btSkipForward.setIcon(icon14)
        self.btSkipForward.setIconSize(QSize(25, 25))
        self.btSkipForward.setFlat(True)

        self.gridControles.addWidget(self.btSkipForward, 1, 5, 1, 1)

        self.btArchivo = QPushButton(self.widgetControles)
        self.btArchivo.setObjectName(u"btArchivo")
        self.btArchivo.setMinimumSize(QSize(37, 37))
        self.btArchivo.setMaximumSize(QSize(37, 16777215))
        self.btArchivo.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon15 = QIcon()
        icon15.addFile(u":/views/icons/file-add.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btArchivo.setIcon(icon15)
        self.btArchivo.setIconSize(QSize(25, 25))
        self.btArchivo.setFlat(True)

        self.gridControles.addWidget(self.btArchivo, 1, 6, 1, 1)

        self.btCarpeta = QPushButton(self.widgetControles)
        self.btCarpeta.setObjectName(u"btCarpeta")
        self.btCarpeta.setMinimumSize(QSize(37, 37))
        self.btCarpeta.setMaximumSize(QSize(37, 16777215))
        self.btCarpeta.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u":/views/icons/add-folder.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btCarpeta.setIcon(icon16)
        self.btCarpeta.setIconSize(QSize(25, 25))
        self.btCarpeta.setFlat(True)

        self.gridControles.addWidget(self.btCarpeta, 1, 7, 1, 1)

        self.btShuffle = QPushButton(self.widgetControles)
        self.btShuffle.setObjectName(u"btShuffle")
        self.btShuffle.setMinimumSize(QSize(37, 37))
        self.btShuffle.setMaximumSize(QSize(37, 16777215))
        self.btShuffle.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u":/views/icons/shuffle-off.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btShuffle.setIcon(icon17)
        self.btShuffle.setIconSize(QSize(25, 25))
        self.btShuffle.setFlat(True)

        self.gridControles.addWidget(self.btShuffle, 1, 8, 1, 1)

        self.btRepetir = QPushButton(self.widgetControles)
        self.btRepetir.setObjectName(u"btRepetir")
        self.btRepetir.setMinimumSize(QSize(37, 37))
        self.btRepetir.setMaximumSize(QSize(37, 16777215))
        self.btRepetir.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon18 = QIcon()
        icon18.addFile(u":/views/icons/repeat.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btRepetir.setIcon(icon18)
        self.btRepetir.setIconSize(QSize(25, 25))
        self.btRepetir.setFlat(True)

        self.gridControles.addWidget(self.btRepetir, 1, 9, 1, 1)

        self.lbTiempo = QLabel(self.widgetControles)
        self.lbTiempo.setObjectName(u"lbTiempo")
        self.lbTiempo.setIndent(14)

        self.gridControles.addWidget(self.lbTiempo, 1, 10, 1, 1)

        self.btLista = QPushButton(self.widgetControles)
        self.btLista.setObjectName(u"btLista")
        self.btLista.setMinimumSize(QSize(37, 37))
        self.btLista.setMaximumSize(QSize(37, 16777215))
        self.btLista.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon19 = QIcon()
        icon19.addFile(u":/views/icons/box-list.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btLista.setIcon(icon19)
        self.btLista.setIconSize(QSize(25, 25))
        self.btLista.setFlat(True)

        self.gridControles.addWidget(self.btLista, 1, 11, 1, 1)

        self.btPanel = QPushButton(self.widgetControles)
        self.btPanel.setObjectName(u"btPanel")
        self.btPanel.setMinimumSize(QSize(37, 37))
        self.btPanel.setMaximumSize(QSize(37, 16777215))
        self.btPanel.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon20 = QIcon()
        icon20.addFile(u":/views/icons/setting.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btPanel.setIcon(icon20)
        self.btPanel.setIconSize(QSize(25, 25))
        self.btPanel.setFlat(True)

        self.gridControles.addWidget(self.btPanel, 1, 12, 1, 1)

        self.btVolumen = QPushButton(self.widgetControles)
        self.btVolumen.setObjectName(u"btVolumen")
        self.btVolumen.setMinimumSize(QSize(37, 37))
        self.btVolumen.setMaximumSize(QSize(37, 16777215))
        self.btVolumen.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon21 = QIcon()
        icon21.addFile(u":/views/icons/volume-medium.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btVolumen.setIcon(icon21)
        self.btVolumen.setIconSize(QSize(25, 25))
        self.btVolumen.setFlat(True)

        self.gridControles.addWidget(self.btVolumen, 1, 13, 1, 1)

        self.slVolumen = QSlider(self.widgetControles)
        self.slVolumen.setObjectName(u"slVolumen")
        self.slVolumen.setMinimumSize(QSize(120, 0))
        self.slVolumen.setMaximumSize(QSize(120, 16777215))
        self.slVolumen.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.slVolumen.setOrientation(Qt.Orientation.Horizontal)

        self.gridControles.addWidget(self.slVolumen, 1, 14, 1, 1)


        self.gridCentral.addWidget(self.widgetControles, 2, 0, 1, 1)

        MainPlayer.setCentralWidget(self.widgetCentral)

        self.retranslateUi(MainPlayer)

        QMetaObject.connectSlotsByName(MainPlayer)
    # setupUi

    def retranslateUi(self, MainPlayer):
        MainPlayer.setWindowTitle(QCoreApplication.translate("MainPlayer", u"MainWindow", None))
        self.lbTitulo.setText(QCoreApplication.translate("MainPlayer", u"Sinergia", None))
        self.lbTituloArchivo.setText(QCoreApplication.translate("MainPlayer", u"11 Proyectos con Interfaz Gr\u00e1fica en Python", None))
        self.lbExtension.setText(QCoreApplication.translate("MainPlayer", u"MP4 ", None))
        self.btPin.setText("")
        self.btMin.setText("")
        self.btMax.setText("")
        self.btSquare.setText("")
        self.btClose.setText("")
        self.lnBuscar.setPlaceholderText(QCoreApplication.translate("MainPlayer", u"Buscar ...", None))
        self.btPrimero.setText("")
        self.btSubir.setText("")
        self.btBajar.setText("")
        self.btUltimo.setText("")
        self.btAgregar.setText(QCoreApplication.translate("MainPlayer", u"A\u00f1adir", None))
        self.btEliminar.setText(QCoreApplication.translate("MainPlayer", u"Eliminar", None))
        self.btOrdenar.setText(QCoreApplication.translate("MainPlayer", u"Ordenar", None))
        self.lbLogo.setText(QCoreApplication.translate("MainPlayer", u"Sinergia ...", None))
        self.lbMetas.setText(QCoreApplication.translate("MainPlayer", u"TextLabel", None))
#if QT_CONFIG(tooltip)
        self.btSkipBack.setToolTip(QCoreApplication.translate("MainPlayer", u"Regresar canci\u00f3n anterior", None))
#endif // QT_CONFIG(tooltip)
        self.btSkipBack.setText("")
#if QT_CONFIG(tooltip)
        self.btBack.setToolTip(QCoreApplication.translate("MainPlayer", u"Regresar sobre misma canci\u00f3n (5,10) segundos", None))
#endif // QT_CONFIG(tooltip)
        self.btBack.setText("")
#if QT_CONFIG(tooltip)
        self.btPlay.setToolTip(QCoreApplication.translate("MainPlayer", u"Reproducir canci\u00f3n", None))
#endif // QT_CONFIG(tooltip)
        self.btPlay.setText("")
#if QT_CONFIG(tooltip)
        self.btStop.setToolTip(QCoreApplication.translate("MainPlayer", u"Detener canci\u00f3n", None))
#endif // QT_CONFIG(tooltip)
        self.btStop.setText("")
#if QT_CONFIG(tooltip)
        self.btForward.setToolTip(QCoreApplication.translate("MainPlayer", u"Continuar sobre misma canci\u00f3n (5,10) segundos", None))
#endif // QT_CONFIG(tooltip)
        self.btForward.setText("")
#if QT_CONFIG(tooltip)
        self.btSkipForward.setToolTip(QCoreApplication.translate("MainPlayer", u"Continuar canci\u00f3n siguiente", None))
#endif // QT_CONFIG(tooltip)
        self.btSkipForward.setText("")
#if QT_CONFIG(tooltip)
        self.btArchivo.setToolTip(QCoreApplication.translate("MainPlayer", u"Agregar Archivo(s)", None))
#endif // QT_CONFIG(tooltip)
        self.btArchivo.setText("")
#if QT_CONFIG(tooltip)
        self.btCarpeta.setToolTip(QCoreApplication.translate("MainPlayer", u"Agregar Carpeta(s)", None))
#endif // QT_CONFIG(tooltip)
        self.btCarpeta.setText("")
#if QT_CONFIG(tooltip)
        self.btShuffle.setToolTip(QCoreApplication.translate("MainPlayer", u"Reproducir aleatoriamente", None))
#endif // QT_CONFIG(tooltip)
        self.btShuffle.setText("")
#if QT_CONFIG(tooltip)
        self.btRepetir.setToolTip(QCoreApplication.translate("MainPlayer", u"Repetir una canci\u00f3n o la lista completa", None))
#endif // QT_CONFIG(tooltip)
        self.btRepetir.setText("")
        self.lbTiempo.setText(QCoreApplication.translate("MainPlayer", u"00:00:00/00:00:00", None))
#if QT_CONFIG(tooltip)
        self.btLista.setToolTip(QCoreApplication.translate("MainPlayer", u"Abrir, cerrar lista", None))
#endif // QT_CONFIG(tooltip)
        self.btLista.setText("")
#if QT_CONFIG(tooltip)
        self.btPanel.setToolTip(QCoreApplication.translate("MainPlayer", u"Abrir panel", None))
#endif // QT_CONFIG(tooltip)
        self.btPanel.setText("")
#if QT_CONFIG(tooltip)
        self.btVolumen.setToolTip(QCoreApplication.translate("MainPlayer", u"Si das clic, enciendes o apagas el volumen", None))
#endif // QT_CONFIG(tooltip)
        self.btVolumen.setText("")
    # retranslateUi

